config/routes.rb
Hippo::Application.routes.draw do

  resources :widgets

  resources :stencils

  root :to => 'static#index'

  match 'demo1' => 'static#demo1'
  match 'demo1/:id/dial' => 'static#demo1_dial'
  match 'demo1/:id/curr_temp' => 'static#demo1_curr_temp', :as => :demo1_curr_temp

  match 'demo2' => 'static#demo2'
  match 'demo2/:id' => 'static#demo2_history'
  match 'demo2/:action/:id' => 'static#history_data', :as => :history_data

  match 'osm' => 'static#osm'

  match 'stencils/:id/display' => 'stencils#display'
  match 'location_map_ajax' => 'stencils#location_map_ajax'
  match 'table_ajax' => 'stencils#table_ajax'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    @widget = Widget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.json
  def new
    @widget = Widget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(params[:widget])

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render json: @widget, status: :created, location: @widget }
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.json
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.haml
= form_for @widget do |f|
  - if @widget.errors.any?
    #error_explanation
      %h2= "#{pluralize(@widget.errors.count, "error")} prohibited this widget from being saved:"
      %ul
        - @widget.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :breed
    = f.number_field :breed
  .field
    = f.label :data
    = f.text_field :data
  .actions
    = f.submit 'Save'

app/views/widgets/_location_map.html.haml
- divid = "LocMap#{widget.id}"
%div{:id => "#{divid}", :style => "height:250px"}

%script{:type => "text/javascript", :src => "http://www.openlayers.org/api/OpenLayers.js"}
   
%script
  var ns_#{widget.id} = {
  foo: function() {

  var count = 0;
  var fromProjection = new OpenLayers.Projection("EPSG:4326");   // Transform from WGS 1984
  var toProjection   = new OpenLayers.Projection("EPSG:900913"); // to Spherical Mercator Projection
  
  map = new OpenLayers.Map("#{divid}");
  var mapnik         = new OpenLayers.Layer.OSM();
  map.addLayer(mapnik);
  
  var markerlayer = new OpenLayers.Layer.Markers("Markers_#{divid}" );
  map.addLayer(markerlayer);
 
  function getMarkers() {
  count = count + 1;
  $.getJSON("/location_map_ajax.json?channels=#{widget.data}", function(data) {
  markerlayer.clearMarkers();
  for (var i=0; i<data.markers.length; i++) {
  position = new OpenLayers.LonLat(data.markers[i]["longitude"], data.markers[i]["latitude"]).transform(fromProjection, toProjection);
  m = new OpenLayers.Marker(position);
  markerlayer.addMarker(m);
  }
  centerposition = new OpenLayers.LonLat(data.centerposition["longitude"], data.centerposition["latitude"]).transform(fromProjection, toProjection);
  map.setCenter(centerposition, data.zoom);
  markerlayer.redraw();
  }); // end function(data)
  };

  getMarkers();
  setInterval("getMarkers()", 30000);
  
  } // end foo()
  } // end ns

  ns_#{widget.id}.foo();
  

app/views/widgets/_table.html.haml
- divid = "Table#{widget.id}"
%div{:id => "#{divid}"}

%script
  var ns_#{widget.id} = {
  foo: function() {

  function cell(ih){
  var tcell =document.createElement('td');
  tcell.innerHTML=ih;
  return tcell;
  };
  
  $.getJSON("/table_ajax.json?channels=#{widget.data}", function(data) {
  mutable=document.createElement('table');
  mutable.className = "table table-striped";
  for (var i=0; i<data.markers.length; i++){
  row1=document.createElement('tr');
  row1.appendChild(cell(data.markers[i]["entry_id"]));
  row1.appendChild(cell(data.markers[i]["latitude"]));
  row1.appendChild(cell(data.markers[i]["longitude"]));
  mutable.appendChild(row1);
  }; // end for
  document.getElementById("#{divid}").appendChild(mutable);
  }); // end function(data)
  } // end foo()
  } // end ns

  ns_#{widget.id}.foo();

app/views/widgets/edit.html.haml
%h1 Editing widget

= render 'form'

= link_to 'Show', @widget
\|
= link_to 'Back', widgets_path

app/views/widgets/index.html.haml
%h1 Listing widgets

%table
  %tr
    %th Breed
    %th Data
    %th
    %th
    %th

  - @widgets.each do |widget|
    %tr
      %td= widget.breed
      %td= widget.data
      %td= link_to 'Show', widget
      %td= link_to 'Edit', edit_widget_path(widget)
      %td= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Widget', new_widget_path

app/views/widgets/new.html.haml
%h1 New widget

= render 'form'

= link_to 'Back', widgets_path

app/views/widgets/show.html.haml
%p#notice= notice

%p
  %b Breed:
  = @widget.breed
%p
  %b Data:
  = @widget.data

= link_to 'Edit', edit_widget_path(@widget)
\|
= link_to 'Back', widgets_path