config/routes.rb
Hippo::Application.routes.draw do

  resources :widgets

  resources :stencils

  root :to => 'static#index'

  match 'demo1' => 'static#demo1'
  match 'demo1/:id/dial' => 'static#demo1_dial'
  match 'demo1/:id/curr_temp' => 'static#demo1_curr_temp', :as => :demo1_curr_temp

  match 'demo2' => 'static#demo2'
  match 'demo2/:id' => 'static#demo2_history'
  match 'demo2/:action/:id' => 'static#history_data', :as => :history_data

  match 'osm' => 'static#osm'

  match 'stencils/:id/display' => 'stencils#display'
  match 'location_map_ajax' => 'stencils#location_map_ajax'
  match 'table_ajax' => 'stencils#table_ajax'

end

app/models/stencil.rb
class Stencil < ActiveRecord::Base
end

app/controllers/stencils_controller.rb
class StencilsController < ApplicationController
  # GET /stencils
  # GET /stencils.json
  def index
    @stencils = Stencil.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stencils }
    end
  end

  # GET /stencils/1
  # GET /stencils/1.json
  def show
    @stencil = Stencil.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stencil }
    end
  end

  # GET /stencils/new
  # GET /stencils/new.json
  def new
    @stencil = Stencil.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stencil }
    end
  end

  # GET /stencils/1/edit
  def edit
    @stencil = Stencil.find(params[:id])
  end

  # POST /stencils
  # POST /stencils.json
  def create
    @stencil = Stencil.new(params[:stencil])

    respond_to do |format|
      if @stencil.save
        format.html { redirect_to @stencil, notice: 'Stencil was successfully created.' }
        format.json { render json: @stencil, status: :created, location: @stencil }
      else
        format.html { render action: "new" }
        format.json { render json: @stencil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stencils/1
  # PUT /stencils/1.json
  def update
    @stencil = Stencil.find(params[:id])

    respond_to do |format|
      if @stencil.update_attributes(params[:stencil])
        format.html { redirect_to @stencil, notice: 'Stencil was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stencil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stencils/1
  # DELETE /stencils/1.json
  def destroy
    @stencil = Stencil.find(params[:id])
    @stencil.destroy

    respond_to do |format|
      format.html { redirect_to stencils_url }
      format.json { head :no_content }
    end
  end

  def display
    @stencil = Stencil.find(params[:id])
    wid_list = @stencil.widgets.split(",").map {|s| s.to_i}
    @widgets = Widget.find(wid_list)
    @widgets.each do |w|
      if w.breed == 1
        # Nothing here (yet)
      end
    end

    stencil_breed_template = "stencils/breed#{@stencil.breed}"
    render :template => stencil_breed_template, :formats => [:html], :handlers => "haml"
  end



  ### AJAX calls made by widgets

  # AJAX function called by location_map Widget
  def location_map_ajax
    channels_str = params[:channels]
    channel_list = channels_str.split(",").map {|s| s.to_i}

    markers = []    
    channel_list.each do |channel|
      json_str = Net::HTTP.get(URI.parse("http://#{THINGSPEAK_SERVER}/channels/#{channel}/feed.json?results=1&location=true"))
      parsed_hash = ActiveSupport::JSON.decode(json_str)
      entry = parsed_hash["feeds"][0]
      markers.push(entry)
    end
    
    # TBD: Determine centerposition and zoom based on all the markers
    centerposition = {}
    centerposition["latitude"] = 12.9833
    centerposition["longitude"] = 77.5833
    zoom = 10

    render :json => {:markers => markers, :centerposition => centerposition, :zoom => zoom}
  end

  # AJAX function called by table Widget
  def table_ajax
    channels_str = params[:channels]
    channel_list = channels_str.split(",").map {|s| s.to_i}

    markers = []    
    channel_list.each do |channel|
      json_str = Net::HTTP.get(URI.parse("http://#{THINGSPEAK_SERVER}/channels/#{channel}/feed.json?results=1&location=true"))
      parsed_hash = ActiveSupport::JSON.decode(json_str)
      entry = parsed_hash["feeds"][0]
      markers.push(entry)
    end

    render :json => {:markers => markers}
  end

end

app/helpers/stencils_helper.rb
module StencilsHelper
end

app/views/stencils/_form.html.haml
= form_for @stencil do |f|
  - if @stencil.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stencil.errors.count, "error")} prohibited this stencil from being saved:"
      %ul
        - @stencil.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :breed
    = f.number_field :breed
  .field
    = f.label :widgets
    = f.text_field :widgets
  .actions
    = f.submit 'Save'

app/views/stencils/breed1.html.haml
%div.well
  %div#widget1container
    - if @widgets[0].breed == 1
      = render :partial => "widgets/location_map", :locals => {:widget => @widgets[0]}
    - if @widgets[0].breed == 2
      = render :partial => "widgets/table", :locals => {:widget => @widgets[0]}

app/views/stencils/breed2.html.haml
%div.row
  %div
    - if @widgets[0].breed == 1
      = render :partial => "widgets/location_map", :locals => {:widget => @widgets[0]}
    - if @widgets[0].breed == 2
      = render :partial => "widgets/table", :locals => {:widget => @widgets[0]}
  %br
  %hr
  %br  
  %div
    - if @widgets[1].breed == 1
      = render :partial => "widgets/location_map", :locals => {:widget => @widgets[1]}
    - if @widgets[1].breed == 2
      = render :partial => "widgets/table", :locals => {:widget => @widgets[1]}

app/views/stencils/edit.html.haml
%h1 Editing stencil

= render 'form'

= link_to 'Show', @stencil
\|
= link_to 'Back', stencils_path

app/views/stencils/index.html.haml
%h1 Listing stencils

%table
  %tr
    %th Breed
    %th Widgets
    %th
    %th
    %th

  - @stencils.each do |stencil|
    %tr
      %td= stencil.breed
      %td= stencil.widgets
      %td= link_to 'Show', stencil
      %td= link_to 'Edit', edit_stencil_path(stencil)
      %td= link_to 'Destroy', stencil, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Stencil', new_stencil_path

app/views/stencils/new.html.haml
%h1 New stencil

= render 'form'

= link_to 'Back', stencils_path

app/views/stencils/show.html.haml
%p#notice= notice

%p
  %b Breed:
  = @stencil.breed
%p
  %b Widgets:
  = @stencil.widgets

= link_to 'Edit', edit_stencil_path(@stencil)
\|
= link_to 'Back', stencils_path